### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by Martinligabue** [iAnonymous3000/popos-hardening-guide#1]
I think a nice way to improve this guide would be to add some examples in steps like "Unnecessary Services", as you're making a guide specifically about PopOS, so you can add some services that are probably not necessary.
Same goes for open ports, antivirus suggestions and how to do audits (like lynis).

**Comment by iAnonymous3000** [comment]
I appreciate your valuable feedback. Your suggestions have been incorporated into the latest version of the guide. Thanks for contributing!
