### ISSUE TITLE
Add the use of NTS instead of NTP for time synchronization

### ISSUE THREAD

**Issue by ghost** [iAnonymous3000/popos-hardening-guide#2]
Hello, first off, I really like your guide about Pop!_OS hardening, that being said. 

It will be great if you can mention the use of NTS instead of NTP for time sync. NTP has many security caveats, while NTS alleviates those issues as it insures the integrity of the data being transmitted.

Actually, the Fedora team has made [a blog post about how to do that on their distro](https://fedoramagazine.org/secure-ntp-with-nts/) by editing `/etc/chrony.conf`. Though, I think it could be possible of doing the same on other distros, such as Ubuntu/Debian-based systems like Pop!_OS.

One feasible thing to do is using GrapheneOS Infrastructure's /etc/chrony.conf file which is already setup to use NTS by using this command : `sudo curl https://raw.githubusercontent.com/GrapheneOS/infrastructure/main/chrony.conf -o /etc/chrony.conf`

Thanks!

**Comment by iAnonymous3000** [comment]
Thanks for your valuable suggestion on NTS. I've updated the guide to include detailed instructions for NTS under 'System Updates'. Please review and continue to provide feedback!
