### ISSUE TITLE
Secure boot

### ISSUE THREAD

**Issue by f-fusco** [iAnonymous3000/popos-hardening-guide#3]
Pop does not support secure boot at this time. Enabling it just sends you back to the BIOS. This line should be updated accordingly.

From https://support.system76.com/articles/install-pop:
"Secure boot must be disabled before installing Pop!_OS. Secure boot can be disabled in the BIOS..."

**Comment by iAnonymous3000** [comment]
Thank you for your feedback. I have made the necessary changes to the hardening guide. The instructions to enable Secure Boot have been removed and it is now clearly stated that it should be disabled on Pop!_OS until official support is added. Please let me know if you come across any other inaccuracies in the guide.
